//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int Id { get; set; }
        public Nullable<double> Serie_id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Serie { get; set; }
        public string Agenda_type { get; set; }
        public string Locatie { get; set; }
        public string Vistijd { get; set; }
        public string Inschr { get; set; }
        public string Vislocatie { get; set; }
        public Nullable<decimal> Inleg { get; set; }
        public string Opmerking { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
