//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BerekenPunten
    {
        public int ID { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<double> Punten { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
