//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatumWeerEtc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatumWeerEtc()
        {
            this.Nachtvissen = new HashSet<Nachtvissen>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDseizoen { get; set; }
        public Nullable<int> SerieNaamNr { get; set; }
        public string SerieNaam { get; set; }
        public Nullable<int> IDserieNummer { get; set; }
        public string Plaats { get; set; }
        public string MB { get; set; }
        public string Wind { get; set; }
        public string WindSnelheid { get; set; }
        public string Temp { get; set; }
        public string DatumVolgende { get; set; }
        public string LocatieVolgende { get; set; }
        public string Inschrijven { get; set; }
        public string Loten { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Weer { get; set; }
        public string StartTijd { get; set; }
        public string EindTijd { get; set; }
        public string Verhaal { get; set; }
        public Nullable<int> Albumid { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual NaamSerie NaamSerie { get; set; }
        public virtual Seizoen Seizoen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nachtvissen> Nachtvissen { get; set; }
    }
}
