//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instellingen
    {
        public string Naam { get; set; }
        public string Email { get; set; }
        public string Krant_email { get; set; }
        public string Krant_onderwerp { get; set; }
        public string Kabelkrant_email { get; set; }
        public string Kabelkrant_onderwerp { get; set; }
        public string Email_cc { get; set; }
        public string SMTP { get; set; }
        public Nullable<int> Poort { get; set; }
        public string Gebruikersnaam { get; set; }
        public string Wachtwoord { get; set; }
        public Nullable<bool> ssl { get; set; }
        public string Locatie_sjablonen { get; set; }
        public string Locatie_afbeeldingen { get; set; }
        public string Fotolinks_jeugd { get; set; }
        public string Fotolinks_senioren { get; set; }
        public string Fotolinks_50_plus { get; set; }
        public string Fotorechts_jeugd { get; set; }
        public string Fotorechts_senioren { get; set; }
        public string Fotorechts_50_plus { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
