//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leden
    {
        public string Lidnummer { get; set; }
        public string Voorletters { get; set; }
        public string Tussenvoegsel { get; set; }
        public string Achternaam { get; set; }
        public string Straat { get; set; }
        public Nullable<int> Huisnummer { get; set; }
        public string Toevoegsel { get; set; }
        public string Postcode { get; set; }
        public string Plaats { get; set; }
        public string Telefoonnummer { get; set; }
        public string Mobiel { get; set; }
        public string Email { get; set; }
        public string IBAN { get; set; }
        public string BIC { get; set; }
        public Nullable<bool> Verwijderd { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
