//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loten
    {
        public int Serieid { get; set; }
        public int Naamid { get; set; }
        public Nullable<int> Sectie1 { get; set; }
        public Nullable<int> Sectie2 { get; set; }
        public Nullable<int> Sectie3 { get; set; }
        public Nullable<int> Sectie4 { get; set; }
        public Nullable<int> Sectie5 { get; set; }
        public Nullable<int> Sectie6 { get; set; }
        public Nullable<int> Sectie7 { get; set; }
        public Nullable<int> Sectie8 { get; set; }
        public Nullable<int> Sectie9 { get; set; }
        public Nullable<int> Sectie10 { get; set; }
        public Nullable<int> Sectie11 { get; set; }
        public Nullable<int> Sectie12 { get; set; }
        public Nullable<int> Sectie13 { get; set; }
        public Nullable<int> Sectie14 { get; set; }
        public Nullable<int> Sectie15 { get; set; }
        public Nullable<int> Sectie16 { get; set; }
        public Nullable<int> Sectie17 { get; set; }
        public Nullable<int> Sectie18 { get; set; }
        public Nullable<int> Sectie19 { get; set; }
        public Nullable<int> Sectie20 { get; set; }
    }
}
