//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotingdeelnemer
    {
        public int Lotingdeelnemerid { get; set; }
        public Nullable<int> Lotingid { get; set; }
        public Nullable<int> NaamID { get; set; }
        public Nullable<int> Plaats { get; set; }
        public string Onderboven { get; set; }
    
        public virtual Lotingdeelnemer Lotingdeelnemer1 { get; set; }
        public virtual Lotingdeelnemer Lotingdeelnemer2 { get; set; }
    }
}
