//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaamSerie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NaamSerie()
        {
            this.DatumWeerEtc = new HashSet<DatumWeerEtc>();
            this.KlassementCorrectie = new HashSet<KlassementCorrectie>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public Nullable<bool> Vissen { get; set; }
        public Nullable<int> Maxaantal { get; set; }
        public Nullable<int> Punten { get; set; }
        public Nullable<bool> Tonen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatumWeerEtc> DatumWeerEtc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlassementCorrectie> KlassementCorrectie { get; set; }
    }
}
