//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Namen
    {
        public Nullable<int> NaamID { get; set; }
        public string Naam { get; set; }
        public string KoppelID { get; set; }
        public string C50Plus { get; set; }
        public string Afbeelding { get; set; }
        public Nullable<bool> Vijftigplus { get; set; }
        public Nullable<bool> Senioren { get; set; }
        public Nullable<bool> Jeugd { get; set; }
        public Nullable<bool> Verwijderd { get; set; }
        public Nullable<bool> Koppelvissen { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsel { get; set; }
        public string Achternaam { get; set; }
        public Nullable<bool> Winter { get; set; }
        public int Id { get; set; }
    }
}
