//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisSeizoenEntities1 : DbContext
    {
        public VisSeizoenEntities1()
            : base("name=VisSeizoenEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<DatumWeerEtc> DatumWeerEtc { get; set; }
        public virtual DbSet<Loten> Loten { get; set; }
        public virtual DbSet<Loting> Loting { get; set; }
        public virtual DbSet<Lotingdeelnemer> Lotingdeelnemer { get; set; }
        public virtual DbSet<NaamSerie> NaamSerie { get; set; }
        public virtual DbSet<Nachtvissen> Nachtvissen { get; set; }
        public virtual DbSet<Namen> Namen { get; set; }
        public virtual DbSet<Seizoen> Seizoen { get; set; }
        public virtual DbSet<SerieNummer> SerieNummer { get; set; }
        public virtual DbSet<Uitslagen> Uitslagen { get; set; }
        public virtual DbSet<Wind> Wind { get; set; }
        public virtual DbSet<BerekenPunten> BerekenPunten { get; set; }
        public virtual DbSet<Instellingen> Instellingen { get; set; }
        public virtual DbSet<Leden> Leden { get; set; }
        public virtual DbSet<KlassementCorrectie> KlassementCorrectie { get; set; }
    }
}
