//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeelnemerJ
    {
        public int NrJ { get; set; }
        public string NaamJ { get; set; }
        public string VolledigeNaamJ { get; set; }
        public string Afbeelding { get; set; }
        public Nullable<bool> Verwijderd { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsel { get; set; }
        public string Achternaam { get; set; }
    }
}
