//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlassementCorrectie
    {
        public int Seizoenid { get; set; }
        public int Serieid { get; set; }
        public Nullable<int> Correctie { get; set; }
        public int Correctieid { get; set; }
    
        public virtual NaamSerie NaamSerie { get; set; }
        public virtual Seizoen Seizoen { get; set; }
    }
}
