//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loting2
    {
        public int Lotingid { get; set; }
        public int Naamid { get; set; }
        public int Seizoenid { get; set; }
        public int Serieid { get; set; }
        public System.DateTime Datum { get; set; }
        public int Nummer { get; set; }
        public int Plaats { get; set; }
        public int Datumid { get; set; }
        public string Serienummer { get; set; }
        public string Onderboven { get; set; }
    }
}
