//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalaag
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int Partnerid { get; set; }
        public int Naamid { get; set; }
        public int Serieid { get; set; }
        public int Partnernaamid { get; set; }
        public int Id { get; set; }
    
        public virtual Namen Namen { get; set; }
    }
}
